### ISSUE TITLE
[BUG] venice-admin-tool doesn't parse map arguments correctly

### ISSUE THREAD

**Issue by ZacAttack** [linkedin/venice#647]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Venice version

All versions

### System information

-- all platforms, this is a code bug --

### The Problem
In venice-admin-tool some commands are meant to take json maps as arguments.  Primary examples of this include using the --update-store command to set a custom partitioner or setting store views.  Unfortunately, right now the tool doesn't parse these well from command line (and it was heretofore undetected because java tests which invoke the api directly don't have this problem).

### Example Input
java -jar venice-admin-tool-all.jar --update-store --url http://venice-controller:1576 --cluster venice-cluster --store TestGpuJobsDataStoreV1 --storage-view-configs '{"changeCaptureView": {"viewClassName": "com.linkedin.venice.views.ChangeCaptureView","params": {}}}'

### Code to reproduce bug

```
zpolicze@zpolicze-mn2 libs % java -jar venice-admin-tool-all.jar --update-store --url http://ltx1-app6326.stg.linkedin.com:1576 --cluster mt-0 --store TestGpuJobsDataStoreV1 -storage-view-configs '{"changeCaptureView": {"viewClassName": "com.linkedin.venice.views.ChangeCaptureView","params": {}}}'
[WARN] Running admin tool without SSL.
{
  "error" : "storage-view-configs must be key value pairs separated by comma, but value: {\"changeCaptureView\": {\"viewClassName\": \"com.linkedin.venice.views.ChangeCaptureView\",\"params\": {}}}"
}
Exception in thread "main" com.linkedin.venice.exceptions.VeniceException: storage-view-configs must be key value pairs separated by comma, but value: {"changeCaptureView": {"viewClassName": "com.linkedin.venice.views.ChangeCaptureView","params": {}}}
	at com.linkedin.venice.utils.Utils.parseCommaSeparatedStringMapFromString(Utils.java:325)
	at com.linkedin.venice.AdminTool.lambda$stringMapParam$7(AdminTool.java:992)
	at com.linkedin.venice.AdminTool.genericParam(AdminTool.java:1010)
	at com.linkedin.venice.AdminTool.stringMapParam(AdminTool.java:992)
	at com.linkedin.venice.AdminTool.getUpdateStoreQueryParams(AdminTool.java:1090)
	at com.linkedin.venice.AdminTool.updateStore(AdminTool.java:1015)
	at com.linkedin.venice.AdminTool.main(AdminTool.java:318)
```

### What component(s) does this bug affect?

- [ ] `Controller`: This is the control-plane for Venice. Used to create/update/query stores and their metadata.
- [ ] `Router`: This is the stateless query-routing layer for serving read requests.
- [ ] `Server`: This is the component that persists all the store data.
- [ ] `VenicePushJob`: This is the component that pushes derived data from Hadoop to Venice backend.
- [ ] `VenicePulsarSink`: This is a Sink connector for Apache Pulsar that pushes data from Pulsar into Venice.
- [ ] `Thin Client`: This is a stateless client users use to query Venice Router for reading store data.
- [ ] `Fast Client`: This is a stateful client users use to query Venice Server for reading store data.
- [ ] `Da Vinci Client`: This is an embedded, stateful client that materializes store data locally.
- [ ] `Alpini`: This is the framework that fast-client and routers use to route requests to the storage nodes that have the data.
- [ ] `Samza`: This is the library users use to make nearline updates to store data.
- [X] `Admin Tool`: This is the stand-alone client used for ad-hoc operations on Venice.
- [ ] `Scripts`: These are the various ops scripts in the repo.

**Comment by ZacAttack** [comment]
This is a great first time contributor bug for those interested!
